FROM alpine:3.24.1

LABEL org.opencontainers.image.title="rTorrent" \
      org.opencontainers.image.description="Current Alpine rTorrent for Flood" \
      org.opencontainers.image.source="https://github.com/rakshasa/rtorrent"

RUN apk add --no-cache ca-certificates rtorrent tzdata \
    && addgroup -g 1001 download \
    && adduser -D -H -u 1001 -G download download

USER 1001:1001
WORKDIR /home/download
ENTRYPOINT ["/usr/bin/rtorrent"]
