services:
  databasus:
    image: databasus/databasus:latest@sha256:7fcac1ccca59fb8bc4e213a00bedde54b4cc323e636f00c573232a9d8a8b216a
    container_name: databasus
    restart: unless-stopped
    cpus: 2.0
    mem_limit: 2g
    memswap_limit: 3g
    pids_limit: 512
    cpu_shares: 256
    env_file:
      - path: ../../shared.env
        required: false
      - stack.env
    volumes:
      - databasus_data:/databasus-data
    networks:
      - ingress-admin
    healthcheck:
      test: ["CMD", "databasus", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: "3"

networks:
  ingress-admin:
    name: ingress-admin
    external: true

volumes:
  databasus_data:
