name: asking-ng secrets

on:
  push:
    paths:
      - "**"
      - ".github/workflows/secrets.yml"
  pull_request:
    paths:
      - "**"
      - ".github/workflows/secrets.yml"

concurrency:
  group: asking-ng-secrets-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
