name: simplelogin
default_port: null
databases:
- postgres
health:
  endpoint: /
  internal_only: false
monitoring:
  prometheus: false
  uptime_kuma:
    external: true
    internal: true
  blackbox_exporter: true
  grafana_dashboard: false
shared_resources: []
type: web_app
category: networking
exposure:
  behind_caddy: true
  public_by_default: false
  recommended_hostname: simplelogin.yourdomain.com
data_profile:
  contains_pii: true
  contains_logs_only: false
  recommended_backup: true
host_requirements:
  needs_gpu: false
  needs_privileged: false
  uses_host_network: false
links:
  homepage: https://simplelogin.io
  docs: https://simplelogin.io/docs
  repo: https://github.com/simple-login/app
backup:
  priority: high
  schedule_hint: weekly
volumes:
- name: simplelogin-data
  role: app_data
  critical: true
- name: simplelogin-upload
  role: app_data
  critical: true
- name: simplelogin-pg18-data
  role: app_data
  critical: true
auth:
  mode: app_local
  sso_provider: null
  access_policy: access_full_site
resources:
  cpu_profile: large
  memory_profile: large
  storage_profile: medium
  gpu_profile: none
placement:
  preferred_node: null
  colocation_group: null
lifecycle:
  status: stable
  replacement_for: null
  notes: ''
runtime_security:
  privileged_services: []
  host_network_services: []
  docker_socket_services: []
  floating_image_services: []
