services:
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2:latest
    container_name: nzbhydra2
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Denver}
    volumes:
      - nzbhydra2_config:/config
    networks:
      - monitor
      - usenet

networks:
  monitor:
    name: monitor
    external: true
  usenet:
    name: usenet
    external: true

volumes:
  nzbhydra2_config:

