name: watchtower
default_port: null
databases: []
health:
  endpoint: /
  internal_only: false
monitoring:
  prometheus: false
  uptime_kuma:
    external: true
    internal: true
  blackbox_exporter: true
  grafana_dashboard: false
shared_resources: []
type: web_app
category: utility
exposure:
  behind_caddy: true
  public_by_default: false
  recommended_hostname: watchtower.yourdomain.com
data_profile:
  contains_pii: false
  contains_logs_only: false
  recommended_backup: false
host_requirements:
  needs_gpu: false
  needs_privileged: false
  uses_host_network: false
links:
  homepage: https://containrrr.dev/watchtower
  docs: https://containrrr.dev/watchtower/
  repo: https://github.com/nickfedor/watchtower
backup:
  priority: low
  schedule_hint: manual
volumes: []
auth:
  mode: app_local
  sso_provider: null
  access_policy: access_full_site
resources:
  cpu_profile: large
  memory_profile: large
  storage_profile: small
  gpu_profile: none
placement:
  preferred_node: null
  colocation_group: null
lifecycle:
  status: stable
  replacement_for: null
  notes: ''
