services:
  trilium:
    image: triliumnext/notes:latest@sha256:611a430016585d35b170eb9a0fa300ce76318f04a8ec0067549c4c52561b0c36
    container_name: trilium
    restart: unless-stopped
    labels:
      - logging=true
      - logging_sampling=false
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - path: ../../shared.env
        required: false
      - stack.env
    volumes:
      - trilium_data:/home/node/trilium-data
    networks:
      - ingress-public
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  ingress-public:
    name: ingress-public
    external: true

volumes:
  trilium_data: {}
