services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    restart: unless-stopped
    volumes:
      - home_assistant_config:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - monitor
    env_file:
      - stack.env
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:8123/api/"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 90s

networks:
  monitor:
    name: monitor
    external: true

volumes:
  home_assistant_config: {}

