# use Node.js 20 (LTS) as base image for compatibility
FROM node:20-alpine as build

# set working directory
WORKDIR /app

# set path
ENV PATH /app/node_modules/.bin:$PATH

# copy dependencies first, and install
COPY package.json .
COPY pnpm-lock.yaml .
RUN corepack enable && pnpm install --frozen-lockfile

# copy rest of files
COPY . .

ARG VITE_API_BASE=/api
ENV VITE_API_BASE=$VITE_API_BASE

# build for production
RUN pnpm build

# production nginx base image
FROM nginx:stable-alpine

# copy built files to nginx public dir
COPY --from=build /app/build /usr/share/nginx/html

# copy modified nginx config over
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# expose port 80
EXPOSE 80

# start nginx server
CMD ["nginx", "-g", "daemon off;"]