name: romm
default_port: null
databases:
- mysql
health:
  endpoint: /
  internal_only: false
monitoring:
  prometheus: false
  uptime_kuma:
    external: true
    internal: true
  blackbox_exporter: true
  grafana_dashboard: false
shared_resources: []
type: web_app
category: dashboard
exposure:
  behind_caddy: true
  public_by_default: false
  recommended_hostname: romm.yourdomain.com
data_profile:
  contains_pii: true
  contains_logs_only: false
  recommended_backup: true
host_requirements:
  needs_gpu: false
  needs_privileged: false
  uses_host_network: false
links:
  homepage: null
  docs: https://docs.romm.app/latest/
  repo: https://github.com/rommapp/romm
backup:
  priority: high
  schedule_hint: weekly
volumes:
- name: romm_mysql12_data
  role: app_data
  critical: true
- name: romm_resources
  role: app_data
  critical: true
- name: romm_data
  role: app_data
  critical: true
- name: romm_config
  role: app_data
  critical: true
- name: romm_library
  role: app_data
  critical: true
- name: romm_assets
  role: app_data
  critical: true
auth:
  mode: builtin
  sso_provider: null
  access_policy: access_full_site
resources:
  cpu_profile: medium
  memory_profile: medium
  storage_profile: medium
  gpu_profile: none
placement:
  preferred_node: null
  colocation_group: null
lifecycle:
  status: stable
  replacement_for: null
  notes: ''
runtime_security:
  privileged_services: []
  host_network_services: []
  docker_socket_services: []
  floating_image_services: []
