name: plex
default_port: 32400
databases: []
health:
  endpoint: /identity
  internal_only: false
monitoring:
  prometheus: false
  uptime_kuma:
    external: true
    internal: true
  blackbox_exporter: true
  grafana_dashboard: false
shared_resources: []
type: web_app
category: media
exposure:
  behind_caddy: true
  public_by_default: false
  recommended_hostname: plex.yourdomain.com
data_profile:
  contains_pii: false
  contains_logs_only: false
  recommended_backup: true
host_requirements:
  needs_gpu: true
  needs_privileged: false
  uses_host_network: false
links:
  homepage: https://www.plex.tv/
  docs: https://support.plex.tv/
  repo: null
backup:
  priority: medium
  schedule_hint: weekly
volumes:
- name: plex_config
  role: app_data
  critical: true
- name: plex_transcode
  role: app_data
  critical: true
- name: media_tv
  role: app_data
  critical: true
- name: external
  role: app_data
  critical: true
- name: media_movies
  role: app_data
  critical: true
- name: external
  role: app_data
  critical: true
- name: media_music
  role: app_data
  critical: true
- name: external
  role: app_data
  critical: true
auth:
  mode: app_local
  sso_provider: null
  access_policy: access_full_site
resources:
  cpu_profile: small
  memory_profile: small
  storage_profile: medium
  gpu_profile: none
placement:
  preferred_node: null
  colocation_group: media
lifecycle:
  status: stable
  replacement_for: null
  notes: ''
