# Generated by scripts/sync-publication-reader.py; edit the native source.
import re
import xml.etree.ElementTree as ET

MAX_XML = 262144


class ComicTree(ET.TreeBuilder):
    """ElementTree cannot retain document-level nodes outside the root."""
    def __init__(self):
        super().__init__(insert_comments=True, insert_pis=True)
        self.depth = 0

    def start(self, tag, attrs):
        self.depth += 1
        return super().start(tag, attrs)

    def end(self, tag):
        result = super().end(tag)
        self.depth -= 1
        return result

    def comment(self, text):
        if not self.depth:
            raise ValueError('Document-level comments cannot be preserved')
        return super().comment(text)

    def pi(self, target, text):
        if not self.depth:
            raise ValueError('Document-level instructions cannot be preserved')
        return super().pi(target, text)


def parse(raw):
    if not isinstance(raw, bytes) or len(raw) > MAX_XML:
        raise ValueError('Invalid metadata size or type')
    try:
        text = raw.decode('utf-8-sig')
        if re.search(r'<!\s*(?:DOCTYPE|ENTITY)\b', text, re.I):
            raise ValueError('DTD and entities are unsupported')
        parser = ET.XMLParser(target=ComicTree())
        root = ET.fromstring(text, parser=parser)
    except (UnicodeError, ET.ParseError) as error:
        raise ValueError('Malformed ComicInfo') from error
    if root.tag != 'ComicInfo':
        raise ValueError('Expected ComicInfo root')
    if (root.text or '').strip():
        raise ValueError('Unsupported text outside metadata fields')
    return root
