# Generated by scripts/sync-publication-reader.py; edit the native source.
import os
import struct

MAX_MEMBERS = 4096


MAX_UNPACKED = 4 * 1024 ** 3


MAX_DIRECTORY = 8 * 1024 ** 2


def directory_limits(stream):
    """Bound ZipFile's central-directory allocation before constructing it."""
    size = os.fstat(stream.fileno()).st_size
    if size > MAX_UNPACKED or size < 22:
        raise ValueError('Unsupported archive size')
    stream.seek(max(0, size - 65557))
    tail = stream.read(65557)
    offset = tail.rfind(b'PK\x05\x06')
    if offset < 0 or len(tail) - offset < 22:
        raise ValueError('Missing archive directory')
    _, disk, start_disk, disk_count, count, length, start, comment = struct.unpack_from('<4s4H2LH', tail, offset)
    footer_offset = size - len(tail) + offset
    # A maximum-length comment leaves the locator outside the tail buffer.
    stream.seek(max(0, footer_offset - 20))
    zip64 = footer_offset >= 20 and stream.read(4) == b'PK\x06\x07'
    if (disk or start_disk or disk_count != count or not 0 < count <= MAX_MEMBERS
            or length > MAX_DIRECTORY or start == 0xffffffff
            or offset + 22 + comment != len(tail)
            or start + length > footer_offset or zip64):
        raise ValueError('Unsupported or oversized archive directory')
    stream.seek(0)
