# Generated by scripts/sync-publication-reader.py; edit the native source.
from contextlib import closing
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import selectors
import stat
import subprocess
import sys
import tarfile
import time
import zipfile

MAX_MEMBERS = 4096


MAX_BYTES = 4 * 1024 ** 3


MAX_MEMBER = 512 * 1024 ** 2


MAX_METADATA = 262144


MAX_OUTPUT = 2 * 1024 ** 2


TIMEOUT = 180


TOOL_ROOT = Path('/opt/archiving-utils')


METADATA = ('ComicInfo.xml', 'ComicBookInfo.json')


PAGE_EXTENSIONS = frozenset(('.jpg', '.jpeg', '.jpe', '.jfif', '.png', '.apng',
    '.webp', '.gif', '.tif', '.tiff', '.bmp', '.dib', '.avif', '.heic', '.heif',
    '.jxl', '.jp2', '.j2k', '.jpf', '.jpx', '.ppm', '.pgm', '.pbm', '.pnm', '.qoi'))


class Unavailable(ValueError):
    """Required complete stable evidence is unavailable; retain the source."""


def compact(value):
    return json.dumps(value, ensure_ascii=False, separators=(',', ':'),
                      allow_nan=False).encode('utf-8')


def signature(info):
    return [info.st_dev, info.st_ino, info.st_size, info.st_mtime_ns,
            info.st_ctime_ns, info.st_mode, info.st_uid, info.st_gid,
            info.st_nlink]


def regular(path):
    path = Path(path)
    if not path.is_absolute() or any(p.is_symlink() for p in (path, *path.parents)):
        raise Unavailable('Expected an absolute unlinked archive path')
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK | os.O_CLOEXEC)
    stream = os.fdopen(fd, 'rb')
    if not stat.S_ISREG(os.fstat(fd).st_mode):
        stream.close()
        raise Unavailable('Expected a regular archive')
    return stream


def file_hash(path, *, deadline=None):
    deadline = time.monotonic() + TIMEOUT if deadline is None else deadline
    with regular(path) as stream:
        before = signature(os.fstat(stream.fileno()))
        if not 0 < before[2] <= MAX_BYTES:
            raise Unavailable('Archive exceeds input bounds')
        digest, count = hashlib.sha256(), 0
        while True:
            if time.monotonic() >= deadline:
                raise Unavailable('Archive hashing timed out')
            block = stream.read(min(1024 * 1024, before[2] - count + 1))
            if not block:
                break
            count += len(block)
            if count > before[2] or count > MAX_BYTES:
                raise Unavailable('Archive grew during verification')
            digest.update(block)
        if (count != before[2] or signature(os.fstat(stream.fileno())) != before
                or signature(Path(path).lstat()) != before):
            raise Unavailable('Archive changed during verification')
    return before, digest.hexdigest()


def object_pairs(pairs):
    value = {}
    for key, item in pairs:
        if key in value:
            raise Unavailable('Duplicate metadata or protocol key')
        value[key] = item
    return value


def decode_json(raw):
    return json.loads(raw, object_pairs_hook=object_pairs,
                      parse_constant=lambda _: (_ for _ in ()).throw(
                          Unavailable('Non-finite JSON value')))


def metadata(name, raw):
    if len(raw) > MAX_METADATA:
        raise Unavailable('Metadata exceeds bounds')
    if name == 'ComicInfo.xml':
        if __package__:
            from .publication_metadata import parse
        else:
            from publication_metadata import parse
        parse(raw)
    else:
        value = decode_json(raw.decode('utf-8-sig'))
        if (not isinstance(value, dict)
                or not isinstance(value.get('ComicBookInfo/1.0'), dict)):
            raise Unavailable('Unsupported ComicBookInfo schema')


def safe_name(name, directory):
    if not isinstance(name, str):
        raise Unavailable('Invalid member name')
    path = PurePosixPath(name)
    canonical = name[:-1] if directory and name.endswith('/') else name
    if (not canonical or canonical != path.as_posix() or path.is_absolute()
            or canonical == '.' or '..' in path.parts
            or any(c in name for c in ('\\', '\0', ':'))
            or len(name.encode('utf-8')) > 4096):
        raise Unavailable('Unsafe or noncanonical member name')
    return canonical


def token(rows, pages):
    members = sorted(([r['name'], r['bytes'], r['sha256']] for r in rows
                      if not r['directory'] and r['name'] not in METADATA),
                     key=lambda row: row[0].encode('utf-8'))
    return hashlib.sha256(compact(dict(version=1, members=members,
                                       pages=pages))).hexdigest()


def natural_key(name):
    return (tuple((1, int(part)) if part.isascii() and part.isdigit() else (0, part)
                  for part in re.split(r'([0-9]+)', name.casefold())), name)


def validate(value):
    if (not isinstance(value, dict) or set(value) != {'version', 'members', 'pages', 'payload'}
            or type(value['version']) is not int or value['version'] != 1
            or not isinstance(value['members'], list)
            or not 0 < len(value['members']) <= MAX_MEMBERS):
        raise Unavailable('Invalid archive verifier schema')
    seen, total, metadata_count = set(), 0, 0
    for row in value['members']:
        if (not isinstance(row, dict) or set(row) != {'name', 'bytes', 'directory', 'sha256'}
                or type(row['directory']) is not bool or type(row['bytes']) is not int
                or not 0 <= row['bytes'] <= MAX_MEMBER
                or not isinstance(row['sha256'], str)
                or not re.fullmatch('[0-9a-f]{64}', row['sha256'])):
            raise Unavailable('Invalid member evidence schema')
        name = safe_name(row['name'], row['directory'])
        if name != row['name'] or name in seen:
            raise Unavailable('Ambiguous member evidence')
        seen.add(name)
        total += row['bytes']
        if total > MAX_BYTES or (row['directory'] and (row['bytes']
                or row['sha256'] != hashlib.sha256(b'').hexdigest())):
            raise Unavailable('Invalid directory or expanded-byte evidence')
        if name.casefold() in {m.casefold() for m in METADATA}:
            metadata_count += 1
            if (name not in METADATA or metadata_count > 1 or row['directory']
                    or row['bytes'] > MAX_METADATA):
                raise Unavailable('Ambiguous metadata evidence')
    pages = sorted((r['name'] for r in value['members'] if not r['directory']
                    and PurePosixPath(r['name']).suffix.lower() in PAGE_EXTENSIONS),
                   key=natural_key)
    if not pages or value['pages'] != pages or value['payload'] != token(value['members'], pages):
        raise Unavailable('Incomplete or unordered payload evidence')


def scan(path, tool_root):
    """Child-only streaming scan. No extraction or tool configuration lookup."""
    root = Path(tool_root).resolve(strict=True)
    sys.path.insert(0, str(root / 'lib'))
    import comics
    if comics.PAGE_EXTENSIONS != PAGE_EXTENSIONS:
        raise Unavailable('Archive verifier page protocol changed')
    from publication_zip import directory_limits
    rows, seen, total, root_metadata = [], set(), 0, []

    def consume(name, size, directory, stream):
        nonlocal total
        name = safe_name(name, directory)
        if name in seen or len(seen) >= MAX_MEMBERS:
            raise Unavailable('Duplicate or excessive archive members')
        seen.add(name)
        if (type(size) is not int or size < 0 or size > MAX_MEMBER
                or total + size > MAX_BYTES or (directory and size)):
            raise Unavailable('Archive exceeds payload bounds')
        total += size
        if name.casefold() in {m.casefold() for m in METADATA}:
            if name not in METADATA or directory or root_metadata:
                raise Unavailable('Ambiguous root metadata')
            root_metadata.append(name)
        limit = MAX_METADATA if name in METADATA else MAX_MEMBER
        if size > limit:
            raise Unavailable('Archive member exceeds bounds')
        digest, count, chunks = hashlib.sha256(), 0, []
        if stream is not None:
            while block := stream.read(min(1024 * 1024, limit - count + 1)):
                count += len(block)
                if count > size or count > limit:
                    raise Unavailable('Archive member exceeds declared size')
                digest.update(block)
                if name in METADATA:
                    chunks.append(block)
        if count != size:
            raise Unavailable('Incomplete archive member')
        if name in METADATA:
            metadata(name, b''.join(chunks))
        rows.append(dict(name=name, bytes=count, directory=directory,
                         sha256=digest.hexdigest()))

    path = Path(path)
    with regular(path) as source:
        magic = source.read(8)
        source.seek(0)
        if magic.startswith(b'PK'):
            directory_limits(source)
            with zipfile.ZipFile(source) as archive:
                for member in archive.infolist():
                    mode = member.external_attr >> 16
                    kind = stat.S_IFMT(mode)
                    directory = member.is_dir()
                    if (member.filename != member.orig_filename
                            or member.flag_bits & 1
                            or kind not in (0, stat.S_IFREG, stat.S_IFDIR)
                            or (kind == stat.S_IFDIR and not directory)
                            or (kind == stat.S_IFREG and directory)
                            or (member.external_attr & 0x10 and not directory)):
                        raise Unavailable('Linked, encrypted or special ZIP member')
                    with archive.open(member) as stream:
                        consume(member.filename, member.file_size, member.is_dir(), stream)
        elif magic.startswith((b'Rar!\x1a\x07', b'7z\xbc\xaf\x27\x1c')):
            from archive_backend import scan as native_scan
            native_scan(path, consume, MAX_MEMBERS)
        else:
            # Compressed TAR wrappers remain unavailable until their complete
            # trailer/integrity is proved. tarfile may stop before that trailer.
            with tarfile.open(fileobj=source, mode='r:') as archive:
                for member in archive:
                    if not (member.isfile() or member.isdir()):
                        raise Unavailable('Linked or special TAR member')
                    if member.isdir():
                        consume(member.name, member.size, True, None)
                    else:
                        with archive.extractfile(member) as stream:
                            consume(member.name, member.size, False, stream)
                source.seek(archive.offset)
                padding = 0
                while block := source.read(1024 * 1024):
                    if block.strip(b'\0'):
                        raise Unavailable('Unverified trailing TAR contents')
                    padding += len(block)
                    if padding > MAX_BYTES:
                        raise Unavailable('TAR padding exceeds bounds')
                if padding < 1024 or padding % 512:
                    raise Unavailable('Missing complete TAR termination')
    pages = sorted((r['name'] for r in rows if not r['directory']
                    and PurePosixPath(r['name']).suffix.lower() in PAGE_EXTENSIONS),
                   key=natural_key)
    if not pages:
        raise Unavailable('Archive has no recognized pages')
    return dict(version=1, members=rows, pages=pages, payload=token(rows, pages))


def bounded_run(command, *, timeout=TIMEOUT, max_output=MAX_OUTPUT):
    """Bound stdout AND stderr allocation and execution, including hung pipes."""
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                               env=dict(os.environ, PYTHONDONTWRITEBYTECODE='1'))
    deadline, output, total = time.monotonic() + timeout, bytearray(), 0
    try:
        with selectors.DefaultSelector() as selector:
            for stream in (process.stdout, process.stderr):
                os.set_blocking(stream.fileno(), False)
                selector.register(stream, selectors.EVENT_READ)
            while selector.get_map():
                remaining = deadline - time.monotonic()
                if remaining <= 0:
                    raise Unavailable('Archive verification timed out')
                for key, _ in selector.select(remaining):
                    block = os.read(key.fileobj.fileno(), 65536)
                    if not block:
                        selector.unregister(key.fileobj)
                        continue
                    total += len(block)
                    if total > max_output:
                        raise Unavailable('Archive verification output exceeds bounds')
                    if key.fileobj is process.stdout:
                        output.extend(block)
            if process.wait(timeout=max(0.001, deadline - time.monotonic())):
                raise Unavailable('Complete archive verification unavailable')
        return bytes(output)
    except subprocess.TimeoutExpired as error:
        raise Unavailable('Archive verification timed out') from error
    finally:
        if process.poll() is None:
            process.kill()
        process.wait()
        process.stdout.close()
        process.stderr.close()


def inventory(path, *, tool_root=TOOL_ROOT, deadline=None):
    """Return full source bindings and payload evidence; never an admission."""
    try:
        deadline = time.monotonic() + TIMEOUT if deadline is None else deadline
        before, digest = file_hash(path, deadline=deadline)
        raw = bounded_run([sys.executable, '-I', str(Path(__file__).resolve()),
                           '--inventory', str(path), str(tool_root)],
                          timeout=max(0.001, deadline - time.monotonic()))
        value = decode_json(raw)
        after, current = file_hash(path, deadline=deadline)
        if before != after or digest != current:
            raise Unavailable('Archive changed during inventory')
        validate(value)
        value.update(source_sha256=digest, source_signature=before)
        return value
    except (OSError, ValueError, TypeError, KeyError, UnicodeError, RecursionError) as error:
        raise Unavailable('Stable complete publication payload evidence unavailable') from error


REGISTRY_LIMIT = 512


REGISTRY_BYTES = 32 * 1024 ** 2


REGISTRATION_INTENT_LIMIT = 640


CATALOG_ROWS = 100000


CATALOG_BYTES = 64 * 1024 ** 2


CATALOG_PATHS = 200000


REGISTRATION_BYTES = 4 * 1024 ** 2


REGISTRY_KINDS = frozenset(('publication_attestation', 'publication_census', 'publication_intent'))


def canonical_digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, ensure_ascii=False,
        separators=(',', ':'), allow_nan=False).encode('utf-8')).hexdigest()


def same_json(left, right):
    """Compare exact JSON types as well as values; bool/float cannot alias int."""
    return canonical_digest(left) == canonical_digest(right)


def digest_value(value):
    return isinstance(value, str) and re.fullmatch('[0-9a-f]{64}', value) is not None


def exact_owner(value):
    fields = {'table', 'issueid', 'parentcomicid', 'releasecomicid'}
    if (not isinstance(value, dict) or set(value) != fields
            or value['table'] not in ('issues', 'annuals')
            or any(not isinstance(value[key], str)
                   or re.fullmatch('[1-9][0-9]{0,15}', value[key]) is None
                   for key in fields - {'table'})
            or (value['table'] == 'issues'
                and value['parentcomicid'] != value['releasecomicid'])):
        raise Unavailable('Invalid exact publication owner')
    return value


def catalog_fact(value, owner):
    """Exact v1 current catalog projection; raw values retain their meaning."""
    fields = {'version', 'comic_location', 'location', 'path', 'status', 'deleted'}
    if (not isinstance(value, dict) or set(value) != fields
            or type(value['version']) is not int or value['version'] != 1
            or any(not isinstance(value[key], str) or not 0 < len(value[key].encode('utf-8')) <= 4096
                   or '\0' in value[key] or '\\' in value[key]
                   for key in ('comic_location', 'location', 'path'))
            or value['status'] not in ('Downloaded', 'Archived')
            or (owner['table'] == 'issues' and value['deleted'] is not None)
            or (owner['table'] == 'annuals' and value['deleted'] is not None
                and (type(value['deleted']) is not int or value['deleted'] != 0))):
        raise Unavailable('Invalid observed catalog facts')
    folder, location, path = (Path(value[key]) for key in ('comic_location', 'location', 'path'))
    if (not folder.is_absolute() or not path.is_absolute()
            or any('..' in item.parts for item in (folder, location, path))
            or str(folder / location) != value['path'] or not path.is_relative_to(folder)):
        raise Unavailable('Unconfined observed catalog facts')
    return value


def _catalog_path(folder, location, roots):
    # Lexical projection precedes bounded metadata checks; no archive reads here.
    if any(not isinstance(value, str) or not 0 < len(value.encode('utf-8')) <= 4096
           or '\0' in value or '\\' in value for value in (folder, location)):
        raise Unavailable('Invalid native catalog path')
    folder, location = Path(folder), Path(location)
    path = folder / location
    if (not folder.is_absolute() or '..' in folder.parts or '..' in location.parts or len(path.parts) > 64
            or not path.is_relative_to(folder) or not any(path.is_relative_to(root) for root in roots)):
        raise Unavailable('Native catalog path is outside configured library roots')
    return path


def _claim_identity(path):
    try:info = path.lstat()
    except FileNotFoundError:return None
    if stat.S_ISLNK(info.st_mode):
        raise Unavailable('Linked native catalog path claim')
    return (info.st_dev, info.st_ino, info.st_mode, info.st_uid, info.st_gid,
            None if stat.S_ISDIR(info.st_mode) else info.st_nlink)


def observe_owners(database, writer, owners, library_roots, *, tool_root=TOOL_ROOT, path_mapper=None, deadline=None):
    """Fresh internal native observation under caller-owned raw Writer.

    Database/roots are trusted native configuration, not request paths. Read
    complete bounded projections without filtering deleted/inactive conflicts.
    Only selected exact current archives are read. No DBConnection or Store,
    initialization, SQLite recovery, archive mutation or eligibility admission.
    """
    import sqlite3
    try:
        def archive_path(path):
            return path if path_mapper is None else path_mapper(path)
        if not getattr(writer.local[1], 'depth', 0):
            raise Unavailable('Raw Writer required before native observation')
        writer_identity(writer)
        database = Path(database)
        if (not database.is_absolute()
                or not isinstance(owners, list) or not 1 <= len(owners) <= 8
                or len({canonical_digest(exact_owner(owner)) for owner in owners}) != len(owners)
                or not isinstance(library_roots, (list, tuple)) or not 1 <= len(library_roots) <= 8):
            raise Unavailable('Invalid native observation scope')
        roots = [Path(root) for root in library_roots]
        if any(not root.is_absolute() or '..' in root.parts or not archive_path(root).is_dir()
               or any(path.is_symlink() for path in (archive_path(root), *archive_path(root).parents)) for root in roots):
            raise Unavailable('Unsafe configured library root')
        sidecars = [Path(str(database) + suffix) for suffix in ('-journal', '-wal', '-shm')]
        with regular(database) as stream:
            before = signature(os.fstat(stream.fileno()))
            header = stream.read(100)
            if (before[6] != os.geteuid() or before[8] != 1 or before[2] > 256 * 1024 ** 2
                    or len(header) != 100 or header[:16] != b'SQLite format 3\0'
                    or header[18:20] != b'\x01\x01' or any(os.path.lexists(path) for path in sidecars)):
                raise Unavailable('Native catalog requires complete rollback-journal state')
            rows, count, size = {}, 0, 0
            deadline = time.monotonic() + TIMEOUT if deadline is None else deadline
            with closing(sqlite3.connect(database.as_uri() + '?mode=ro&immutable=1', uri=True)) as db:
                db.set_progress_handler(lambda: int(time.monotonic() >= deadline), 1000)
                db.execute('BEGIN')
                if db.execute('PRAGMA quick_check').fetchall() != [('ok',)]:
                    raise Unavailable('Unreadable native catalog')
                for table, fields in (('comics', ('ComicID', 'ComicLocation')),
                        ('issues', ('IssueID', 'ComicID', 'Location', 'Status')),
                        ('annuals', ('IssueID', 'ComicID', 'ReleaseComicID', 'Location', 'Status', 'Deleted'))):
                    if db.execute('SELECT type FROM sqlite_master WHERE name=?', (table,)).fetchall() != [('table',)]:
                        raise Unavailable('Unsupported native catalog projection')
                    total, bytes_used = db.execute('SELECT count(*),coalesce(sum(' +
                        '+'.join('coalesce(length(CAST('+field+' AS BLOB)),0)' for field in fields) +
                        '),0) FROM '+table).fetchone()
                    count += total;size += bytes_used
                    if count > CATALOG_ROWS or size > CATALOG_BYTES:
                        raise Unavailable('Native catalog projection exceeds bounds')
                    rows[table] = [dict(zip(fields, row)) for row in db.execute('SELECT '+','.join(fields)+' FROM '+table)]
                    for row in rows[table]:
                        if any(value is not None and not isinstance(value, str)
                               for key, value in row.items() if key != 'Deleted'):
                            raise Unavailable('Malformed native catalog projection')
                        if table == 'annuals' and row['Deleted'] is not None and type(row['Deleted']) is not int:
                            raise Unavailable('Malformed annual deletion flag')
            def remaining():
                if time.monotonic() >= deadline:
                    raise Unavailable('Native observation timed out')
            parents = {}
            for row in rows['comics']:
                remaining();parents.setdefault(row['ComicID'], []).append(row)
            issues = [(table, row) for table in ('issues', 'annuals') for row in rows[table]]
            claims, physical, identities = {}, {}, {}
            identity_bytes = 0
            for table, row in issues:
                remaining()
                if row['Location'] is None or row['Location'] == '':continue
                parent = parents.get(row['ComicID'], [])
                if len(parent) != 1:
                    raise Unavailable('Missing or ambiguous native catalog parent')
                path = _catalog_path(parent[0]['ComicLocation'], row['Location'], roots)
                for component in (path, *path.parents):
                    remaining()
                    if component not in identities:
                        identity_bytes += len(os.fsencode(component))
                        if len(identities) >= CATALOG_PATHS or identity_bytes > CATALOG_BYTES:
                            raise Unavailable('Native catalog path identities exceed bounds')
                        identities[component] = _claim_identity(archive_path(component))
                claims.setdefault(str(path), []).append((table, row))
                if identities[path] is not None:
                    physical.setdefault(identities[path][:2], []).append((table, row))
            observed, payload = [], None
            for owner in owners:
                remaining()
                matched = [(table, row) for table, row in issues if row['IssueID'] == owner['issueid']]
                if len(matched) != 1 or matched[0][0] != owner['table']:
                    raise Unavailable('Ambiguous native issue/annual owner')
                table, row = matched[0]
                parent = parents.get(owner['parentcomicid'], [])
                if (row['ComicID'] != owner['parentcomicid'] or len(parent) != 1
                        or (table == 'annuals' and row['ReleaseComicID'] != owner['releasecomicid'])):
                    raise Unavailable('Changed native parent/release owner')
                path = _catalog_path(parent[0]['ComicLocation'], row['Location'], roots)
                current_identity = identities.get(path)
                if (len(claims.get(str(path), [])) != 1 or current_identity is None
                        or len(physical.get(current_identity[:2], [])) != 1):
                    raise Unavailable('Ambiguous native current path owner')
                facts = dict(version=1, comic_location=parent[0]['ComicLocation'], location=row['Location'],
                             path=str(path), status=row['Status'], deleted=row.get('Deleted'))
                catalog_fact(facts, owner)
                value = inventory(archive_path(path), tool_root=tool_root, deadline=deadline)
                current = {key: value[key] for key in ('version', 'members', 'pages', 'payload')}
                if payload is not None and payload['payload'] != current['payload']:
                    raise Unavailable('Correct owners have different publication payloads')
                if payload is None:payload = current
                observed.append(dict(owner=dict(owner), source_sha256=value['source_sha256'],
                                     signature=value['source_signature'], catalog=facts))
            if (signature(os.fstat(stream.fileno())) != before or signature(database.lstat()) != before
                    or any(os.path.lexists(path) for path in sidecars)):
                raise Unavailable('Native catalog changed during observation')
            for facts in observed:
                remaining()
                path = archive_path(Path(facts['catalog']['path']))
                if (any(part.is_symlink() for part in (path, *path.parents))
                        or signature(path.lstat()) != facts['signature']):
                    raise Unavailable('Native correct source changed during observation')
            for path, identity in identities.items():
                remaining()
                if _claim_identity(archive_path(path)) != identity:
                    raise Unavailable('Native catalog path identity changed during observation')
            writer_identity(writer)
            return dict(inventory=payload, observed=observed)
    except (OSError, sqlite3.Error, ValueError, TypeError, KeyError, UnicodeError, RecursionError) as error:
        raise Unavailable('Fresh native correct-owner observation unavailable') from error


def attestation(value):
    fields = {'version', 'epoch', 'prior_revision', 'inventory', 'allowed',
              'rejected', 'evidence', 'observed', 'intent', 'created'}
    if (not isinstance(value, dict) or set(value) != fields
            or type(value['version']) is not int or value['version'] != 1
            or not digest_value(value['epoch']) or not digest_value(value['intent'])
            or type(value['prior_revision']) is not int or value['prior_revision'] < 0
            or type(value['created']) is not int or value['created'] < 0):
        raise Unavailable('Invalid correction attestation')
    validate(value['inventory'])
    owners = []
    for kind in ('allowed', 'rejected'):
        group = value[kind]
        if not isinstance(group, list) or not group or len(group) > 8:
            raise Unavailable('Correction requires bounded explicit owners')
        owners.extend(canonical_digest(exact_owner(owner)) for owner in group)
    if len(owners) > 8 or len(owners) != len(set(owners)):
        raise Unavailable('Duplicate or contradictory correction owners')
    evidence = value['evidence']
    if (not isinstance(evidence, dict) or set(evidence) != {'sha256', 'description'}
            or not digest_value(evidence['sha256'])
            or not isinstance(evidence['description'], str)
            or not 1 <= len(evidence['description'].encode('utf-8')) <= 2048):
        raise Unavailable('Invalid reviewed evidence binding')
    observed = value['observed']
    if not isinstance(observed, list) or len(observed) != len(value['allowed']):
        raise Unavailable('Missing observed correct-owner facts')
    for owner, facts in zip(value['allowed'], observed):
        if (not isinstance(facts, dict)
                or set(facts) != {'owner', 'source_sha256', 'signature', 'catalog'}
                or facts['owner'] != owner or not digest_value(facts['source_sha256'])
                or not isinstance(facts['signature'], list)
                or len(facts['signature']) != 9
                or any(type(v) is not int or v < 0 for v in facts['signature'])
                or not isinstance(facts['catalog'], dict)):
            raise Unavailable('Invalid observed correct-owner facts')
        catalog_fact(facts['catalog'], owner)
    return canonical_digest(value)


def complete_census(db, *, pending=None):
    """Validate all authority rows in one caller-owned SQLite read snapshot."""
    count, size = db.execute("SELECT count(*),coalesce(sum(length(CAST(value AS BLOB))),0) "
        "FROM records WHERE substr(CAST(kind AS TEXT),1,12)='publication_'").fetchone()
    if count > REGISTRY_LIMIT + INTENT_LIMIT + REGISTRATION_INTENT_LIMIT + 1 or size > REGISTRY_BYTES:
        raise Unavailable('Correction census exceeds v1 bounds')
    rows = db.execute("SELECT kind,key,value FROM records WHERE substr(CAST(kind AS TEXT),1,12)='publication_' "
                      'ORDER BY kind,key').fetchmany(REGISTRY_LIMIT + INTENT_LIMIT + REGISTRATION_INTENT_LIMIT + 2)
    if len(rows) > REGISTRY_LIMIT + INTENT_LIMIT + REGISTRATION_INTENT_LIMIT + 1:
        raise Unavailable('Correction census exceeds v1 bounds')
    records, census, size, intents = {}, None, 0, {}
    intent_counts = {'bootstrap': 0, 'register': 0}
    for kind, key, raw in rows:
        if any(not isinstance(value, str) for value in (kind, key, raw)):
            raise Unavailable('Malformed correction authority record')
        size += len(raw.encode('utf-8'))
        if size > REGISTRY_BYTES or kind not in REGISTRY_KINDS:
            raise Unavailable('Unknown or oversized correction authority')
        value = decode_json(raw)
        if kind == 'publication_intent':
            plan = intent_record(key, value)
            action = plan['action']
            limit = INTENT_LIMIT if action == 'bootstrap' else REGISTRATION_INTENT_LIMIT
            byte_limit = 65536 if action == 'bootstrap' else REGISTRATION_BYTES
            intent_counts[action] += 1
            if intent_counts[action] > limit or len(raw.encode('utf-8')) > byte_limit:
                raise Unavailable('Correction intent history exceeds bounds')
            if value['outcome'] == 'accepted' and not (action == 'register' and key == pending):
                raise Unavailable('Unfinished correction intent blocks admission')
            intents[key] = value
            continue
        if kind == 'publication_census':
            if key != 'v1' or census is not None:
                raise Unavailable('Ambiguous correction census')
            census = value
        else:
            if not digest_value(key) or key != attestation(value):
                raise Unavailable('Correction attestation digest mismatch')
            if key in records:
                raise Unavailable('Duplicate correction attestation key')
            records[key] = value
    if len(records) > REGISTRY_LIMIT:
        raise Unavailable('Correction attestation census exceeds bounds')
    census_value(census)
    if census['revision'] != len(records) or census['keys'] != sorted(records):
        raise Unavailable('Missing or incomplete correction census')
    committed = {key: value for key, value in intents.items()
                 if value['plan']['action'] == 'register' and value['outcome'] == 'committed'}
    current = empty_census(census['epoch'])
    witnessed = set()
    for value in sorted(records.values(), key=lambda item: item['prior_revision']):
        token = value['intent']
        if token not in committed or token in witnessed:
            raise Unavailable('Missing unique committed registration witness')
        plan = committed[token]['plan']
        materialized, new = registration_effect(token, plan)
        if materialized != value or plan['old'] != current:
            raise Unavailable('Incomplete registration revision chain')
        witnessed.add(token)
        current = new
    if witnessed != set(committed) or current != census:
        raise Unavailable('Orphan registration witness or incomplete census chain')
    revisions, payload_owners = set(), {}
    for value in records.values():
        if value['epoch'] != census['epoch']:
            raise Unavailable('Foreign correction epoch')
        revisions.add(value['prior_revision'])
        payload = value['inventory']['payload']
        allowed, rejected = payload_owners.setdefault(payload, (set(), set()))
        allowed.update(canonical_digest(owner) for owner in value['allowed'])
        rejected.update(canonical_digest(owner) for owner in value['rejected'])
        if allowed & rejected:
            raise Unavailable('Contradictory immutable correction history')
    if revisions != set(range(census['revision'])):
        raise Unavailable('Missing correction revision history')
    return census, records


def registry_snapshot(database, marker):
    """Read existing authority only; prepared/missing state never admits media.

    The eventual writer adapter must hold its Writer before calling this helper.
    This function neither initializes nor recovers authority and never opens Store.
    """
    if __package__:
        from .publication_lock import LOCK
    else:
        from publication_lock import LOCK
    with LOCK:
        return _registry_snapshot(database, marker)


def _registry_snapshot(database, marker):
    import sqlite3
    database, marker = Path(database), Path(marker)
    try:
        if os.path.lexists(marker.parent / 'publication-recovery-v1.json'):
            raise Unavailable('Explicit journal recovery is unfinished')
        with regular(database) as stream, regular(marker) as binding:
            before = signature(os.fstat(stream.fileno()))
            mark_before = signature(os.fstat(binding.fileno()))
            for info in (before, mark_before):
                if info[6] != os.geteuid() or stat.S_IMODE(info[5]) != 0o600 or info[8] != 1:
                    raise Unavailable('Correction authority must be private and owned')
            sidecars = [Path(str(database) + suffix) for suffix in ('-wal', '-shm', '-journal')]
            header = stream.read(100)
            if (len(header) != 100 or header[:16] != b'SQLite format 3\0'
                    or header[18:20] != b'\x01\x01'
                    or any(os.path.lexists(path) for path in sidecars)):
                raise Unavailable('Correction authority requires complete rollback-journal state')
            raw = binding.read(MARKER_BYTES + 1)
            if len(raw) > MARKER_BYTES:
                raise Unavailable('Oversized correction marker')
            value = decode_json(raw.decode('utf-8'))
            with closing(sqlite3.connect(database.as_uri() + '?mode=ro&immutable=1', uri=True)) as db:
                db.execute('BEGIN')
                if db.execute('PRAGMA quick_check').fetchall() != [('ok',)]:
                    raise Unavailable('Unreadable correction database')
                census, records = complete_census(db)
                if __package__:
                    from .media_writer import Writer
                else:
                    from media_writer import Writer
                current_writer = writer_identity(Writer(marker.parent, create=False))
                if not isinstance(value, dict) or not digest_value(value.get('initialization_intent')):
                    raise Unavailable('Missing initialization witness binding')
                initialization_witness(db, value['initialization_intent'], census, before[:2], current_writer)
            expected = dict(version=1, phase='final', census=census,
                            initialization_intent=value['initialization_intent'],
                            database_identity=before[:2], writer_identity=current_writer)
            if canonical_digest(value) != canonical_digest(expected):
                raise Unavailable('Correction marker does not bind complete final state')
            if (signature(os.fstat(stream.fileno())) != before
                    or signature(database.lstat()) != before
                    or signature(os.fstat(binding.fileno())) != mark_before
                    or signature(marker.lstat()) != mark_before
                    or any(os.path.lexists(path) for path in sidecars)):
                raise Unavailable('Correction authority changed during read')
            return census, records
    except (OSError, sqlite3.Error, UnicodeError, ValueError, TypeError, KeyError, RecursionError) as error:
        raise Unavailable('Correction authority unavailable') from error


INTENT_LIMIT = 128


MARKER_BYTES = 131072


def writer_identity(writer):
    if __package__:
        from .media_writer import checked_file
    else:
        from media_writer import checked_file
    writer.validate_root()
    fd = checked_file(writer.lock)
    try:
        info = os.fstat(fd)
        lock = (info.st_dev, info.st_ino)
        if lock != writer.lock_identity:
            raise Unavailable('Writer lock identity changed')
        return list(writer.root_identity) + list(lock)
    finally:
        os.close(fd)


def empty_census(epoch):
    return dict(version=1, epoch=epoch, revision=0, keys=[], digest=canonical_digest([]))


def state_binding(binding):
    if (not isinstance(binding, dict)
            or set(binding) != {'database_identity', 'writer_identity', 'schema', 'workflow', 'pending'}
            or not digest_value(binding['schema'])):
        raise Unavailable('Invalid initialization state binding')
    for field, count in (('database_identity', 2), ('writer_identity', 4)):
        items = binding[field]
        if (not isinstance(items, list) or len(items) != count
                or any(type(item) is not int or item < 0 for item in items)):
            raise Unavailable('Invalid initialization filesystem identity')
    workflow = binding['workflow']
    if (not isinstance(workflow, dict) or set(workflow) != {'version', 'count', 'digest'}
            or type(workflow['version']) is not int or workflow['version'] != 1
            or type(workflow['count']) is not int or not 0 <= workflow['count'] <= 100000
            or not digest_value(workflow['digest'])):
        raise Unavailable('Invalid protected workflow binding')
    pending = binding['pending']
    if not isinstance(pending, dict) or set(pending) != {'normalizer', 'tagger', 'release'}:
        raise Unavailable('Invalid existing publication fence binding')
    for stamp in pending.values():
        if stamp is not None and (not isinstance(stamp, list) or len(stamp) != 9
                or any(type(item) is not int or item < 0 for item in stamp)):
            raise Unavailable('Invalid existing publication fence signature')
    return binding


def census_value(value):
    fields = {'version', 'epoch', 'revision', 'keys', 'digest'}
    if (not isinstance(value, dict) or set(value) != fields
            or type(value['version']) is not int or value['version'] != 1
            or not digest_value(value['epoch'])
            or type(value['revision']) is not int or not 0 <= value['revision'] <= REGISTRY_LIMIT
            or not isinstance(value['keys'], list)
            or any(not digest_value(key) for key in value['keys'])
            or value['keys'] != sorted(set(value['keys']))
            or len(value['keys']) != value['revision']
            or value['digest'] != canonical_digest(value['keys'])):
        raise Unavailable('Missing or incomplete correction census')
    return value


def registration_effect(key, plan):
    """Derive effects after hashing a plan, avoiding an intent/attestation cycle."""
    if (not isinstance(plan, dict) or set(plan) != {'version', 'action', 'old', 'binding', 'body'}
            or type(plan['version']) is not int or plan['version'] != 1
            or plan['action'] != 'register' or not digest_value(key)
            or key != canonical_digest(plan)):
        raise Unavailable('Invalid immutable registration plan')
    old = census_value(plan['old'])
    state_binding(plan['binding'])
    body = plan['body']
    if (not isinstance(body, dict) or 'intent' in body
            or body.get('epoch') != old['epoch']
            or body.get('prior_revision') != old['revision']
            or old['revision'] >= REGISTRY_LIMIT):
        raise Unavailable('Invalid registration predecessor')
    value = dict(body, intent=key)
    record_key = attestation(value)
    if record_key in old['keys']:
        raise Unavailable('Duplicate registration effect')
    keys = sorted(old['keys'] + [record_key])
    new = dict(version=1, epoch=old['epoch'], revision=old['revision'] + 1,
               keys=keys, digest=canonical_digest(keys))
    return value, new


def intent_record(key, value):
    if (not isinstance(value, dict) or set(value) != {'plan', 'accepted', 'outcome'}
            or type(value['accepted']) is not bool
            or value['outcome'] not in ('prepared', 'accepted', 'committed', 'aborted')
            or value['accepted'] != (value['outcome'] != 'prepared')
            or not isinstance(value['plan'], dict)):
        raise Unavailable('Invalid correction intent receipt')
    if value['plan'].get('action') == 'bootstrap':
        return bootstrap_record(key, value)
    registration_effect(key, value['plan'])
    return value['plan']


def bootstrap_record(key, value):
    if (not isinstance(value, dict) or set(value) != {'plan', 'accepted', 'outcome'}
            or type(value['accepted']) is not bool
            or value['outcome'] not in ('prepared', 'accepted', 'committed', 'aborted')
            or value['accepted'] != (value['outcome'] != 'prepared')):
        raise Unavailable('Invalid initialization receipt')
    plan = value['plan']
    if (not isinstance(plan, dict)
            or set(plan) != {'version', 'action', 'epoch', 'binding', 'backup', 'new'}
            or type(plan['version']) is not int or plan['version'] != 1
            or plan['action'] != 'bootstrap' or not digest_value(plan['epoch'])
            or canonical_digest(plan['new']) != canonical_digest(empty_census(plan['epoch']))
            or key != canonical_digest(plan)):
        raise Unavailable('Invalid immutable initialization plan')
    state_binding(plan['binding'])
    backup = plan['backup']
    if (not isinstance(backup, dict)
            or set(backup) != {'manifest_sha256', 'restore_sha256', 'description'}
            or not digest_value(backup['manifest_sha256']) or not digest_value(backup['restore_sha256'])
            or not isinstance(backup['description'], str)
            or not 1 <= len(backup['description'].encode('utf-8')) <= 1024):
        raise Unavailable('Reviewed restore evidence is required')
    return plan


def workflow_schema(db):
    tables = {row[0] for row in db.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    columns = [tuple(row) for row in db.execute('PRAGMA table_info(records)')]
    expected = [(0, 'kind', 'TEXT', 1, None, 1), (1, 'key', 'TEXT', 1, None, 2),
                (2, 'value', 'TEXT', 1, None, 0), (3, 'updated', 'REAL', 1, None, 0)]
    if (tables != {'events', 'records'} or columns != expected
            or db.execute("SELECT count(*) FROM sqlite_master WHERE type IN ('view','trigger')").fetchone()[0]):
        raise Unavailable('Unsupported workflow authority schema')
    return canonical_digest([list(row) for row in db.execute(
        'SELECT type,name,tbl_name,sql FROM sqlite_master ORDER BY type,name')])


def initialization_witness(db, token, census, identity, writer, *, pending=None):
    rows = db.execute("SELECT key,value FROM records WHERE kind='publication_intent'").fetchall()
    committed = []
    for key, raw in rows:
        value = decode_json(raw)
        plan = intent_record(key, value)
        if value['outcome'] == 'accepted' and not (plan['action'] == 'register' and key == pending):
            raise Unavailable('Unfinished initialization blocks admission')
        if value['outcome'] == 'committed':
            if plan['action'] == 'bootstrap':
                committed.append(key)
            epoch = plan['epoch'] if plan['action'] == 'bootstrap' else plan['old']['epoch']
            if ((plan['action'] == 'bootstrap' and key != token) or epoch != census['epoch']
                    or plan['binding']['database_identity'] != identity
                    or plan['binding']['writer_identity'] != writer
                    or plan['binding']['schema'] != workflow_schema(db)):
                raise Unavailable('Foreign initialization witness')
    if committed != [token]:
        raise Unavailable('Missing unique committed initialization witness')

if __name__ == '__main__':
    import resource
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    resource.setrlimit(resource.RLIMIT_AS, (512 * 1024 ** 2, 512 * 1024 ** 2))
    resource.setrlimit(resource.RLIMIT_CPU, (120, 120))
    if len(sys.argv) != 4 or sys.argv[1] != '--inventory':
        sys.exit(2)
    try:
        sys.stdout.buffer.write(compact(scan(sys.argv[2], sys.argv[3])))
    except Exception:
        # Protocol failures reveal neither filesystem paths nor private member names.
        sys.exit(1)
