services:
  rtorrent-flood:
    image: lscr.io/linuxserver/rtorrent-flood:latest
    container_name: rtorrent-flood
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Denver}
    volumes:
      - rtorrent_flood_config:/config
      - torrents_manual:/downloads
    networks:
      - monitor
      - torrents
    ports:
      - "49160:49160"
      - "49160:49160/udp"

networks:
  monitor:
    name: monitor
    external: true
  torrents:
    name: torrents
    external: true

volumes:
  rtorrent_flood_config:
  torrents_manual:
    external: true

