#!/usr/bin/env python3
"""Generate the worker's read-only correction verifier from native sources.

The independent Docker context contains no registry transaction implementation.
Only the selected read-side definitions are copied; this script is checked by
repository validation so native protocol changes cannot leave a stale worker.
"""
import argparse
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NATIVE = ROOT / 'stacks/mylar3/config'
WORKER = ROOT / 'stacks/komga/normalizer'
HEADER = '# Generated by scripts/sync-publication-reader.py; edit the native source.\n'


def definitions(filename, names):
    source = (NATIVE / filename).read_text()
    lines = source.splitlines(keepends=True)
    result, found = [], set()
    for node in ast.parse(source).body:
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)):
            selected = {node.name} & names
        elif isinstance(node, ast.Assign):
            selected = {target.id for target in node.targets if isinstance(target, ast.Name)} & names
        else:
            selected = set()
        if selected:
            found.update(selected)
            result.append(''.join(lines[node.lineno - 1:node.end_lineno]))
    if found != names:
        raise ValueError('Native reader definitions changed: ' + str(sorted(names - found)))
    return '\n\n'.join(result).rstrip() + '\n'


def outputs():
    source = (NATIVE / 'publication_guard.py').read_text()
    tree = ast.parse(source)
    # Everything before the mutation/recovery classes is evidence or validation.
    names = set(('Unavailable compact signature regular file_hash object_pairs decode_json metadata '
                 'safe_name token natural_key validate scan bounded_run inventory canonical_digest same_json '
                 'digest_value exact_owner catalog_fact _catalog_path _claim_identity observe_owners attestation '
                 'media_snapshot cleanup_admission _cleanup_admission complete_census registry_snapshot _registry_snapshot writer_identity empty_census state_binding '
                 'census_value registration_effect intent_record bootstrap_record workflow_schema '
                 'initialization_witness').split())
    names.update(('MAX_MEMBERS MAX_BYTES MAX_MEMBER MAX_METADATA MAX_OUTPUT TIMEOUT TOOL_ROOT METADATA '
                  'PAGE_EXTENSIONS REGISTRY_LIMIT REGISTRY_BYTES REGISTRATION_INTENT_LIMIT CATALOG_ROWS '
                  'CATALOG_BYTES CATALOG_PATHS REGISTRATION_BYTES REGISTRY_KINDS INTENT_LIMIT MARKER_BYTES').split())
    imports = ''.join(ast.get_source_segment(source, node) + '\n' for node in tree.body
                      if isinstance(node, (ast.Import, ast.ImportFrom)))
    reader = imports + '\n' + definitions('publication_guard.py', names)
    reader = reader.replace('from .publication_derivative import', 'from .publication_derivative_evidence import')
    reader = reader.replace('from publication_derivative import', 'from publication_derivative_evidence import')
    reader = reader.replace('from .tagger_metadata import parse', 'from .publication_metadata import parse')
    reader = reader.replace('from tagger_metadata import parse', 'from publication_metadata import parse')
    reader = reader.replace('from tagger_archive import directory_limits', 'from publication_zip import directory_limits')
    reader = reader.replace('from .workflow_store import LOCK', 'from .publication_lock import LOCK')
    reader = reader.replace('from workflow_store import LOCK', 'from publication_lock import LOCK')
    reader = reader.replace('from contextlib import closing, contextmanager', 'from contextlib import closing')
    # The worker has two existing mounts of native config/writer state and a
    # trusted explicit media mapping. It never accepts a tagging capability.
    old = 'tool_root=TOOL_ROOT, transaction=None):'
    assert reader.count(old) == 1
    reader = reader.replace(old, 'tool_root=TOOL_ROOT, path_mapper=None, deadline=None):')
    start = reader.index('        if transaction is not None:')
    end = reader.index("        if not getattr(writer.local", start)
    reader = reader[:start] + ('        def archive_path(path):\n'
                               '            return path if path_mapper is None else path_mapper(path)\n') + reader[end:]
    reader = reader.replace(' or database.parent != writer.root.parent', '')
    reader = reader.replace('            if transaction is not None:admission(transaction,writer)\n', '')
    old_roots = '''or not root.is_dir()
               or any(path.is_symlink() for path in (root, *root.parents))'''
    assert reader.count(old_roots) == 1
    reader = reader.replace(old_roots, '''or not archive_path(root).is_dir()
               or any(path.is_symlink() for path in (archive_path(root), *archive_path(root).parents))''')
    old_deadline = '            deadline = time.monotonic() + TIMEOUT\n'
    observe_start = reader.index('def observe_owners(')
    observe_end = reader.find('\ndef ', observe_start + 1)
    if observe_end < 0:
        observe_end = len(reader)
    observation = reader[observe_start:observe_end]
    assert observation.count(old_deadline) == 1
    observation = observation.replace(old_deadline, '            deadline = time.monotonic() + TIMEOUT if deadline is None else deadline\n')
    reader = reader[:observe_start] + observation + reader[observe_end:]
    assert not any(isinstance(node, ast.Name) and node.id in {'transaction', 'admission'}
                   for node in ast.walk(ast.parse(reader)))
    # Exact read-only native owner resolution includes deleted and locationless
    # shadows. Never infer annual release ownership from worker metadata.
    owner = definitions('publication_native.py', {'owner'})
    assert owner.startswith('def owner(')
    owner = owner.replace('def owner(', 'def catalog_owner(', 1).replace('guard.', '')
    reader += '\nimport sqlite3\n\n' + owner
    main = source[source.index("if __name__ == '__main__':"):]
    metadata = 'import re\nimport xml.etree.ElementTree as ET\n\n' + definitions(
        'tagger_metadata.py', {'MAX_XML', 'ComicTree', 'parse'})
    zipper = 'import os\nimport struct\n\n' + definitions(
        'tagger_archive.py', {'MAX_MEMBERS', 'MAX_UNPACKED', 'MAX_DIRECTORY', 'directory_limits'})
    return {'publication_evidence.py': HEADER + reader + '\n' + main,
            'publication_metadata.py': HEADER + metadata,
            'publication_zip.py': HEADER + zipper}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, content in outputs().items():
        path = WORKER / name
        if args.check:
            if not path.is_file() or path.read_text() != content:
                raise SystemExit('Stale publication reader: ' + str(path.relative_to(ROOT)))
        else:
            path.write_text(content)


if __name__ == '__main__':
    main()
