name: theharvester

services:
  theharvester:
    image: secsi/restfulharvest:latest
    container_name: theharvester
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      - TZ=${TZ:-America/Denver}
    networks:
      - proxy-ingress

networks:
  proxy-ingress:
    name: proxy-ingress
    external: true
