name: theharvester

services:
  theharvester:
    image: secsi/restfulharvest:latest
    container_name: theharvester
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      - TZ=${TZ:-America/Denver}
    networks:
      - security-research
      - ingress-admin

networks:
  security-research:
    name: security-research
    external: true
  ingress-admin:
    name: ingress-admin
    external: true
