services:
  pocketbase:
    labels:
      logging: "true"
    image: coollabsio/pocketbase:latest@sha256:e2bc5f75a123f226999096c9efc4479de21ca8420f75238b9992ac33c353c57e
    container_name: pocketbase
    restart: unless-stopped
    cpus: 1.0
    mem_limit: 1g
    memswap_limit: 1536m
    pids_limit: 256
    cpu_shares: 256
    env_file:
      - path: ../../shared.env
        required: false
      - path: stack.env
        required: false
    volumes:
      - pocketbase-data:/pb/pb_data
    networks:
      - ingress-public
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O- http://127.0.0.1:8080/api/health | grep -q 'API is healthy'",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  ingress-public:
    name: ingress-public
    external: true

volumes:
  pocketbase-data:
