services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Denver}
    volumes:
      - bazarr_config:/config
      - media_tv:/tv
      - media_movies:/movies
    networks:
      - monitor

networks:
  monitor:
    name: monitor
    external: true

volumes:
  bazarr_config:
  media_tv:
    external: true
  media_movies:
    external: true

