name: matomo
default_port: 80
databases: []
health:
  endpoint: /
  internal_only: false
monitoring:
  prometheus: false
  uptime_kuma:
    external: true
    internal: true
  blackbox_exporter: true
  grafana_dashboard: false
shared_resources:
- monitor
type: web_app
category: analytics
exposure:
  behind_caddy: true
  public_by_default: false
  recommended_hostname: matomo.yourdomain.com
data_profile:
  contains_pii: false
  contains_logs_only: false
  recommended_backup: true
host_requirements:
  needs_gpu: false
  needs_privileged: false
  uses_host_network: false
links:
  homepage: https://matomo.org
  docs: https://matomo.org/docs/
  repo: https://github.com/matomo-org/matomo
backup:
  priority: medium
  schedule_hint: weekly
volumes:
- name: matomo_matomo_db12
  role: app_data
  critical: true
- name: matomo_matomo_html
  role: app_data
  critical: true
auth:
  mode: app_local
  sso_provider: null
  access_policy: access_full_site
resources:
  cpu_profile: medium
  memory_profile: medium
  storage_profile: medium
  gpu_profile: none
placement:
  preferred_node: null
  colocation_group: null
lifecycle:
  status: stable
  replacement_for: null
  notes: ''
